version: "3"
name: itam-dev-bot
volumes:
  redis:
  redis-config:
  postgres-data:

services:
  redis:
    image: redis:latest
    command: redis-server
    restart: unless-stopped
    volumes:
      - "redis:/var/lib/redis"
      - "redis-config:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
        TZ: 'GMT+3'
        PGTZ: 'GMT+3'
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
  bot:
      build:
        context: ../
        dockerfile: ./docker/Dockerfile
      restart: unless-stopped
      env_file:
        - ../.env
      environment:
        - "POSTGRES_HOST=postgres"
        - "POSTGRES_PORT=5432"
        - "REDIS_HOST=redis"
        - "TZ=Europe/Moscow"
      volumes:
        - ../:/code
      command: python3 src/main.py
      depends_on:
        - postgres
        - redis
